defaults:
  - ./base.yaml

case_name: scan63
root_dir: /data1/zzy/public_data/DTU/DTU/${case_name}
pipeline:
  depth_ratio: 1.0
  mesh_res: 1024
  voxel_size: 0.004
  sdf_trunc: 0.016
  depth_trunc: 3.0
dataset:
  use_alpha: True
  eval: False
  type: all

optimizer:
  percent_dense: 0.0001
  densify_grad_threshold: 0.5
  curvature_clamp_threshold: -10.0
  lambda_dist: 50000.0

model_path: > 
  ${root_dir}/exp/DepthRatio=${pipeline.depth_ratio}_
  DensifyGrad=${optimizer.densify_grad_threshold}_
  CurvClamp=${optimizer.curvature_clamp_threshold}_
  Dist=${optimizer.lambda_dist}_
  Percendent=${optimizer.percent_dense}
# path to pre-trained model
load_model_path: ${root_dir}/exp/DepthRatio=1.0_DensifyGrad=0.5_CurvClamp=-10.0_Dist=50000.0_Percendent=0.0001
# path to directory containing "Calibration, Cleaned, ObsMask, Points, Rectified, Surfaces"
dataset_GT_path: /data1/zzy/public_data/DTU/SampleSet/MVS_Data