defaults:
  - ./base.yaml

skip_train: True
skip_test: True
skip_mesh: False
skip_cull: False
render_path: False
# case_name: Barn
# case_name: Truck
# case_name: Caterpillar
# case_name: Ignatius
# case_name: Meetingroom
case_name: Courthouse
root_dir: /data1/zzy/public_data/TNT/TNT_GOF/TrainingSet/${case_name}

GT_path:
pipeline:
  # num_cluster: 1
  # depth_ratio: 1.0
  # mesh_res: 1024
  # voxel_size: 0.004
  # sdf_trunc: 0.016
  # depth_trunc: 3.5

  num_cluster: 1
  depth_ratio: 0.5
  mesh_res: 1024
  voxel_size: 0.006
  sdf_trunc: 0.024
  depth_trunc: 4.5
dataset:
  use_alpha: False
  eval: False
  downsample: 0.5

optimizer:
  iterations: 60000
  position_lr_max_steps: 60000
  densification_interval: 400
  opacity_reset_interval: 6000
  densify_from_iter: 4000
  normal_from_iter: 30000
  dist_from_iter: 12000
  densify_until_iter: 48000
  reset_opacity_densify_delay: 2
  percent_dense: 0.0001
  densify_grad_threshold: 0.2
  curvature_clamp_threshold: -2.0
  lambda_dist: 10.0

model_path: > 
  ${root_dir}/exp/DepthRatio=${pipeline.depth_ratio}_
  DensifyGrad=${optimizer.densify_grad_threshold}_
  CurvClamp=${optimizer.curvature_clamp_threshold}_
  Dist=${optimizer.lambda_dist}_
  Percendent=${optimizer.percent_dense}
# path to pre-trained model
load_model_path: ${root_dir}/exp/DepthRatio=1.0_DensifyGrad=0.2_CurvClamp=-5.0_Dist=500.0_Percendent=0.0001

# eval mesh
# dataset_GT_path: the path to directory containing xxx_trans.txt, xxx.ply, xxx.json, xxx_COLMAP_SfM.log
dataset_GT_path: /data1/zzy/public_data/TNT/TNT_GOF/TrainingSet/GT/${case_name}
traj_path: ${root_dir}/${case_name}_COLMAP_SfM.log
# mesh_ply_path: the path to directory containing mesh to evaluate
mesh_ply_path: ${load_model_path}/train/ours_30000/fuse_post.ply
eval_output_path: ${load_model_path}/train/ours_30000